/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class DetalleInfraccion extends javax.swing.JFrame {

    /**
     * Creates new form GestionarPartidos
     */
    public DetalleInfraccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDetalleInfraccion = new javax.swing.JLabel();
        btnSalirDetalleInfraccion = new javax.swing.JButton();
        lblCriticaInfraccion = new javax.swing.JLabel();
        lblSignoInfraccion = new javax.swing.JLabel();
        cboxMotivoInfraccion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtACriticaInfraccion = new javax.swing.JTextArea();
        lblAdvertenciaInfraccion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDetalleInfraccion.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblDetalleInfraccion.setText("detalle INFRACCION");
        lblDetalleInfraccion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblDetalleInfraccionInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblDetalleInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btnSalirDetalleInfraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btnSalirDetalleInfraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDetalleInfraccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalirDetalleInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 25, 25));

        lblCriticaInfraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribir.png"))); // NOI18N
        jPanel1.add(lblCriticaInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 39, 42));

        lblSignoInfraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/signo.png"))); // NOI18N
        jPanel1.add(lblSignoInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 39, 42));

        cboxMotivoInfraccion.setEnabled(false);
        jPanel1.add(cboxMotivoInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 400, -1));

        txtACriticaInfraccion.setColumns(20);
        txtACriticaInfraccion.setRows(5);
        txtACriticaInfraccion.setEnabled(false);
        jScrollPane1.setViewportView(txtACriticaInfraccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 400, 190));

        lblAdvertenciaInfraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/advertencia.png"))); // NOI18N
        jPanel1.add(lblAdvertenciaInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 590, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDetalleInfraccionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblDetalleInfraccionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDetalleInfraccionInputMethodTextChanged

    private void btnSalirDetalleInfraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDetalleInfraccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirDetalleInfraccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleInfraccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalirDetalleInfraccion;
    public javax.swing.JComboBox cboxMotivoInfraccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvertenciaInfraccion;
    private javax.swing.JLabel lblCriticaInfraccion;
    private javax.swing.JLabel lblDetalleInfraccion;
    private javax.swing.JLabel lblSignoInfraccion;
    public javax.swing.JTextArea txtACriticaInfraccion;
    // End of variables declaration//GEN-END:variables
}
