/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class DetalleCalificaciones extends javax.swing.JFrame {

    /**
     * Creates new form GestionarPartidos
     */
    public DetalleCalificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDetalleCalificacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalleCalificacion = new javax.swing.JTable();
        btnSalirDetalleCalificaciones = new javax.swing.JButton();
        txtNombreDetalleCalificacion = new javax.swing.JTextField();
        lblNombreDetalleCalificacion = new javax.swing.JLabel();
        lblFotoJugadorDetalleCalificacion = new javax.swing.JLabel();
        lblDocumentoDetalleCalificacion = new javax.swing.JLabel();
        txtIdentificacionDetalleCalificacion = new javax.swing.JTextField();
        lblPromedioDetalleCalificacion = new javax.swing.JLabel();
        txtPromedioDetalleCalificacion = new javax.swing.JTextField();
        lblImagenDetalleCalificaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDetalleCalificacion.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblDetalleCalificacion.setText("DETALLE CALIFICACIONES");
        lblDetalleCalificacion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblDetalleCalificacionInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetalleCalificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Puntaje", "Relato", "Fecha"
            }
        ));
        tableDetalleCalificacion.setEnabled(false);
        jScrollPane2.setViewportView(tableDetalleCalificacion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 230));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 760, 250));

        btnSalirDetalleCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirDetalleCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 25, 25));

        txtNombreDetalleCalificacion.setEnabled(false);
        jPanel1.add(txtNombreDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 250, 30));

        lblNombreDetalleCalificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreDetalleCalificacion.setText("Nombre:");
        jPanel1.add(lblNombreDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 115, -1, -1));

        lblFotoJugadorDetalleCalificacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblFotoJugadorDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 135, 184));

        lblDocumentoDetalleCalificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDocumentoDetalleCalificacion.setText("Documento:");
        jPanel1.add(lblDocumentoDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 175, -1, -1));

        txtIdentificacionDetalleCalificacion.setEnabled(false);
        jPanel1.add(txtIdentificacionDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 250, 30));

        lblPromedioDetalleCalificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPromedioDetalleCalificacion.setText("Promedio:");
        jPanel1.add(lblPromedioDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 235, -1, -1));

        txtPromedioDetalleCalificacion.setEnabled(false);
        jPanel1.add(txtPromedioDetalleCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 250, 30));

        lblImagenDetalleCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion_2.png"))); // NOI18N
        jPanel1.add(lblImagenDetalleCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 618, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDetalleCalificacionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblDetalleCalificacionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDetalleCalificacionInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleCalificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalirDetalleCalificaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetalleCalificacion;
    private javax.swing.JLabel lblDocumentoDetalleCalificacion;
    public javax.swing.JLabel lblFotoJugadorDetalleCalificacion;
    public javax.swing.JLabel lblImagenDetalleCalificaciones;
    private javax.swing.JLabel lblNombreDetalleCalificacion;
    private javax.swing.JLabel lblPromedioDetalleCalificacion;
    public javax.swing.JTable tableDetalleCalificacion;
    public javax.swing.JTextField txtIdentificacionDetalleCalificacion;
    public javax.swing.JTextField txtNombreDetalleCalificacion;
    public javax.swing.JTextField txtPromedioDetalleCalificacion;
    // End of variables declaration//GEN-END:variables
}
