/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class GestionarJugadores extends javax.swing.JFrame {

    /**
     * Creates new form GestionarPartidos
     */
    public GestionarJugadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGestionJugadores = new javax.swing.JLabel();
        btnConsultarJugador = new javax.swing.JButton();
        btnAgregarJugador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJugadores = new javax.swing.JTable();
        btnSalirGestionJugadores = new javax.swing.JButton();
        lblIdentificacionJugadorGestion = new javax.swing.JLabel();
        txtIdentificacionJugadorGestion = new javax.swing.JTextField();
        lblImagenJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestionJugadores.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblGestionJugadores.setText("GESTION                        JUGADORES");
        lblGestionJugadores.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblGestionJugadoresInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblGestionJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnConsultarJugador.setBackground(new java.awt.Color(0, 204, 0));
        btnConsultarJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarJugador.setText("CONSULTAR");
        btnConsultarJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConsultarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        btnAgregarJugador.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        jPanel1.add(btnAgregarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Telefono", "Email", "Ver Detalle", "Modificar", "Eliminar"
            }
        ));
        jScrollPane2.setViewportView(tableJugadores);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 740, 250));

        btnSalirGestionJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirGestionJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 25, 25));

        lblIdentificacionJugadorGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/identificacion.png"))); // NOI18N
        jPanel1.add(lblIdentificacionJugadorGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 39, 42));

        txtIdentificacionJugadorGestion.setText("Identificacion");
        jPanel1.add(txtIdentificacionJugadorGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, 30));

        lblImagenJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugador.png"))); // NOI18N
        jPanel1.add(lblImagenJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, -6, 680, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGestionJugadoresInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblGestionJugadoresInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionJugadoresInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnConsultarJugador;
    private javax.swing.JButton btnSalirGestionJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGestionJugadores;
    private javax.swing.JLabel lblIdentificacionJugadorGestion;
    private javax.swing.JLabel lblImagenJugador;
    private javax.swing.JTable tableJugadores;
    private javax.swing.JTextField txtIdentificacionJugadorGestion;
    // End of variables declaration//GEN-END:variables
}
