/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class GestionarCalificacionesJugador extends javax.swing.JFrame {

    /**
     * Creates new form GestionarPartidos
     */
    public GestionarCalificacionesJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGestionCalificacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCalificacionJugador = new javax.swing.JTable();
        btnSalirGestionCalificacionJugador = new javax.swing.JButton();
        btnAgregarCalificacionJugador = new javax.swing.JButton();
        lblImagenCalificaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestionCalificacion.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblGestionCalificacion.setText("GESTION CALIFICACIONES");
        lblGestionCalificacion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblGestionCalificacionInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblGestionCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCalificacionJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Puntaje", "Reseña"
            }
        ));
        jScrollPane2.setViewportView(tableCalificacionJugador);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 760, 250));

        btnSalirGestionCalificacionJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirGestionCalificacionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 25, 25));

        btnAgregarCalificacionJugador.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarCalificacionJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarCalificacionJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAgregarCalificacionJugador.setText("Agregar Calificacion");
        jPanel1.add(btnAgregarCalificacionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblImagenCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion_1.png"))); // NOI18N
        jPanel1.add(lblImagenCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 618, 443));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGestionCalificacionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblGestionCalificacionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGestionCalificacionInputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarCalificacionJugador;
    public javax.swing.JButton btnSalirGestionCalificacionJugador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGestionCalificacion;
    private javax.swing.JLabel lblImagenCalificaciones;
    public javax.swing.JTable tableCalificacionJugador;
    // End of variables declaration//GEN-END:variables
}
