/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class InformacionJugador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public InformacionJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenPerfilJugador = new javax.swing.JLabel();
        lblBienvenidoPerfilJugador = new javax.swing.JLabel();
        lblNombreBienvenidoPerfilJugador = new javax.swing.JLabel();
        lblPerfilJugador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNombrePerfilJugador = new javax.swing.JLabel();
        lblApellidoPerfilJugador = new javax.swing.JLabel();
        lblDocumentoPerfilJugador = new javax.swing.JLabel();
        lblTelefonoPerfilJugador = new javax.swing.JLabel();
        lblMailPerfilJugador = new javax.swing.JLabel();
        lblModoPerfilJugador = new javax.swing.JLabel();
        lblSuscripcionPerfilJugador = new javax.swing.JLabel();
        txtNombrePerfilJugador = new javax.swing.JTextField();
        txtApellidoPerfilJugador = new javax.swing.JTextField();
        txtDocumentoPerfilJugador = new javax.swing.JTextField();
        txtTelefonoPerfilJugador = new javax.swing.JTextField();
        txtMailPerfilJugador = new javax.swing.JTextField();
        txtModoPerfilJugador = new javax.swing.JTextField();
        txtSuscripcionJugador = new javax.swing.JTextField();
        btnSalirPerfilJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(127, 187, 133));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenPerfilJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lblImagenPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 135, 184));

        lblBienvenidoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBienvenidoPerfilJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenidoPerfilJugador.setText("BIENVENIDO");
        jPanel2.add(lblBienvenidoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblNombreBienvenidoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombreBienvenidoPerfilJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBienvenidoPerfilJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBienvenidoPerfilJugador.setText("JUGADOR");
        jPanel2.add(lblNombreBienvenidoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        lblPerfilJugador.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblPerfilJugador.setText("PERFIL DEL JUGADOR");
        jPanel1.add(lblPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombrePerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombrePerfilJugador.setText("Nombre:");
        jPanel3.add(lblNombrePerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblApellidoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApellidoPerfilJugador.setText("Apellido:");
        jPanel3.add(lblApellidoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblDocumentoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDocumentoPerfilJugador.setText("Documento:");
        jPanel3.add(lblDocumentoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblTelefonoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTelefonoPerfilJugador.setText("Telefono:");
        jPanel3.add(lblTelefonoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblMailPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMailPerfilJugador.setText("E-mail:");
        jPanel3.add(lblMailPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblModoPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModoPerfilJugador.setText("Modo:");
        jPanel3.add(lblModoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblSuscripcionPerfilJugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSuscripcionPerfilJugador.setText("Suscripcion:");
        jPanel3.add(lblSuscripcionPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtNombrePerfilJugador.setEnabled(false);
        jPanel3.add(txtNombrePerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 5, 280, -1));

        txtApellidoPerfilJugador.setEnabled(false);
        jPanel3.add(txtApellidoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 45, 280, -1));

        txtDocumentoPerfilJugador.setEnabled(false);
        jPanel3.add(txtDocumentoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 85, 280, -1));

        txtTelefonoPerfilJugador.setEnabled(false);
        jPanel3.add(txtTelefonoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 125, 280, -1));

        txtMailPerfilJugador.setEnabled(false);
        jPanel3.add(txtMailPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 165, 280, -1));

        txtModoPerfilJugador.setEnabled(false);
        jPanel3.add(txtModoPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 205, 280, -1));

        txtSuscripcionJugador.setEnabled(false);
        jPanel3.add(txtSuscripcionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 245, 280, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 520, 300));

        btnSalirPerfilJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirPerfilJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 5, 25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalirPerfilJugador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApellidoPerfilJugador;
    private javax.swing.JLabel lblBienvenidoPerfilJugador;
    private javax.swing.JLabel lblDocumentoPerfilJugador;
    public javax.swing.JLabel lblImagenPerfilJugador;
    private javax.swing.JLabel lblMailPerfilJugador;
    private javax.swing.JLabel lblModoPerfilJugador;
    public javax.swing.JLabel lblNombreBienvenidoPerfilJugador;
    private javax.swing.JLabel lblNombrePerfilJugador;
    private javax.swing.JLabel lblPerfilJugador;
    private javax.swing.JLabel lblSuscripcionPerfilJugador;
    private javax.swing.JLabel lblTelefonoPerfilJugador;
    public javax.swing.JTextField txtApellidoPerfilJugador;
    public javax.swing.JTextField txtDocumentoPerfilJugador;
    public javax.swing.JTextField txtMailPerfilJugador;
    public javax.swing.JTextField txtModoPerfilJugador;
    public javax.swing.JTextField txtNombrePerfilJugador;
    public javax.swing.JTextField txtSuscripcionJugador;
    public javax.swing.JTextField txtTelefonoPerfilJugador;
    // End of variables declaration//GEN-END:variables
}
