/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class MenuJugador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenJugador = new javax.swing.JLabel();
        btnSalirMenuJugador = new javax.swing.JButton();
        lblCerrarSesion = new javax.swing.JLabel();
        lblBienvenidoJugador = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();
        lblNombreFutbolCopa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBajaJugador = new javax.swing.JButton();
        lblGestionarAusenciaJugador = new javax.swing.JLabel();
        btnInfraccionJugador = new javax.swing.JButton();
        lblGestionarInfraccionJugador = new javax.swing.JLabel();
        btnCalificacionesJugador = new javax.swing.JButton();
        lblGestionarCalificacionesJugador = new javax.swing.JLabel();
        btnSalirMenuJugadorr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(127, 187, 133));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(lblImagenJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 135, 184));

        btnSalirMenuJugador.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirMenuJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalirMenuJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnSalirMenuJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 44, 45));

        lblCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("Cerrar Sesión");
        jPanel2.add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        lblBienvenidoJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBienvenidoJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenidoJugador.setText("BIENVENIDO");
        jPanel2.add(lblBienvenidoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setText("JUGADOR");
        jPanel2.add(lblJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 265, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        lblNombreFutbolCopa.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblNombreFutbolCopa.setText("FUTBOL COPA");
        jPanel1.add(lblNombreFutbolCopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBajaJugador.setBackground(new java.awt.Color(153, 255, 153));
        btnBajaJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBajaJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/baja.png"))); // NOI18N
        btnBajaJugador.setText("Baja");
        btnBajaJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajaJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnBajaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 120));

        lblGestionarAusenciaJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGestionarAusenciaJugador.setForeground(new java.awt.Color(153, 153, 153));
        lblGestionarAusenciaJugador.setText("Gestionar Ausencia");
        jPanel3.add(lblGestionarAusenciaJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 190, 130, -1));

        btnInfraccionJugador.setBackground(new java.awt.Color(255, 153, 153));
        btnInfraccionJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnInfraccionJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/infraccion.png"))); // NOI18N
        btnInfraccionJugador.setText("Infraccion");
        btnInfraccionJugador.setFocusTraversalPolicyProvider(true);
        btnInfraccionJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfraccionJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnInfraccionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 100, 120));

        lblGestionarInfraccionJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGestionarInfraccionJugador.setForeground(new java.awt.Color(153, 153, 153));
        lblGestionarInfraccionJugador.setText("Gestionar Infraccion");
        jPanel3.add(lblGestionarInfraccionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, -1));

        btnCalificacionesJugador.setBackground(new java.awt.Color(255, 255, 153));
        btnCalificacionesJugador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalificacionesJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calificacion.png"))); // NOI18N
        btnCalificacionesJugador.setText("Calificacion");
        btnCalificacionesJugador.setFocusTraversalPolicyProvider(true);
        btnCalificacionesJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalificacionesJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnCalificacionesJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, 120));

        lblGestionarCalificacionesJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGestionarCalificacionesJugador.setForeground(new java.awt.Color(153, 153, 153));
        lblGestionarCalificacionesJugador.setText("Gestionar Calificacion");
        jPanel3.add(lblGestionarCalificacionesJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 140, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 520, 300));

        btnSalirMenuJugadorr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirMenuJugadorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 5, 25, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBajaJugador;
    public javax.swing.JButton btnCalificacionesJugador;
    public javax.swing.JButton btnInfraccionJugador;
    public javax.swing.JButton btnSalirMenuJugador;
    public javax.swing.JButton btnSalirMenuJugadorr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBienvenidoJugador;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblGestionarAusenciaJugador;
    private javax.swing.JLabel lblGestionarCalificacionesJugador;
    private javax.swing.JLabel lblGestionarInfraccionJugador;
    public javax.swing.JLabel lblImagenJugador;
    public javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblNombreFutbolCopa;
    // End of variables declaration//GEN-END:variables
}
