/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author hp
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public Notificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenAdmin = new javax.swing.JLabel();
        btnMail = new javax.swing.JButton();
        lblMailTorneo = new javax.swing.JLabel();
        lblBienvenidoAdmin = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDestinatario = new javax.swing.JLabel();
        lblAsunto = new javax.swing.JLabel();
        lblDestinatario1 = new javax.swing.JLabel();
        lblAsunto1 = new javax.swing.JLabel();
        lblDestinatario2 = new javax.swing.JLabel();
        lblAsunto2 = new javax.swing.JLabel();
        lblDestinatario3 = new javax.swing.JLabel();
        lblAsunto3 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblFecha3 = new javax.swing.JLabel();
        lblDestinatario4 = new javax.swing.JLabel();
        lblAsunto4 = new javax.swing.JLabel();
        lblFecha4 = new javax.swing.JLabel();
        lblDestinatario5 = new javax.swing.JLabel();
        lblAsunto5 = new javax.swing.JLabel();
        lblFecha5 = new javax.swing.JLabel();
        btnSalirMail = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txtConsultarMail = new javax.swing.JTextField();
        btnConsultarMail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(127, 187, 133));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario_admin.png"))); // NOI18N
        jPanel2.add(lblImagenAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 92, 92));

        btnMail.setBackground(new java.awt.Color(255, 255, 255));
        btnMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mail.png"))); // NOI18N
        btnMail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 44, 45));

        lblMailTorneo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMailTorneo.setForeground(new java.awt.Color(255, 255, 255));
        lblMailTorneo.setText("Mail Torneo");
        jPanel2.add(lblMailTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lblBienvenidoAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBienvenidoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenidoAdmin.setText("BIENVENIDO");
        jPanel2.add(lblBienvenidoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("ADMIN");
        jPanel2.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDestinatario.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear_1.png"))); // NOI18N
        lblDestinatario.setText("Sistema Futbol Copa");
        lblDestinatario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 35));

        lblAsunto.setText("     Partido Creado con exito");
        lblAsunto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 260, 35));

        lblDestinatario1.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sancionar.png"))); // NOI18N
        lblDestinatario1.setText("Sistema Futbol Copa");
        lblDestinatario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 200, 35));

        lblAsunto1.setText("     Un jugador se ha dado de baja");
        lblAsunto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 35, 260, 35));

        lblDestinatario2.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confirmar_1.png"))); // NOI18N
        lblDestinatario2.setText("Sistema Futbol Copa");
        lblDestinatario2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 35));

        lblAsunto2.setText("     Equipo Completo");
        lblAsunto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 260, 35));

        lblDestinatario3.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.png"))); // NOI18N
        lblDestinatario3.setText("Sistema Futbol Copa");
        lblDestinatario3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 200, 35));

        lblAsunto3.setText("     Aceptar jugadores");
        lblAsunto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 105, 260, 35));

        lblFecha1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha1.setText("  30 nov");
        lblFecha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 35, 60, 35));

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha.setText("  30 nov");
        lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 60, 35));

        lblFecha2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha2.setText("  30 nov");
        lblFecha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 60, 35));

        lblFecha3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha3.setText("  30 nov");
        lblFecha3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 105, 60, 35));

        lblDestinatario4.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear_1.png"))); // NOI18N
        lblDestinatario4.setText("Sistema Futbol Copa");
        lblDestinatario4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 35));

        lblAsunto4.setText("     Partido Creado con exito");
        lblAsunto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 260, 35));

        lblFecha4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha4.setText("  29 nov");
        lblFecha4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 60, 35));

        lblDestinatario5.setBackground(new java.awt.Color(204, 204, 255));
        lblDestinatario5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDestinatario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confirmar_1.png"))); // NOI18N
        lblDestinatario5.setText("Sistema Futbol Copa");
        lblDestinatario5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblDestinatario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 200, 35));

        lblAsunto5.setText("     Equipo Completo");
        lblAsunto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblAsunto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 175, 260, 35));

        lblFecha5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblFecha5.setText("  29 nov");
        lblFecha5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(lblFecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 175, 60, 35));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 520, 300));

        btnSalirMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jPanel1.add(btnSalirMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 5, 25, 25));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 39, 42));
        jPanel1.add(txtConsultarMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 250, 30));

        btnConsultarMail.setBackground(new java.awt.Color(0, 204, 0));
        btnConsultarMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarMail.setText("CONSULTAR");
        btnConsultarMail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConsultarMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarMail;
    public javax.swing.JButton btnMail;
    public javax.swing.JButton btnSalirMail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblAsunto1;
    private javax.swing.JLabel lblAsunto2;
    private javax.swing.JLabel lblAsunto3;
    private javax.swing.JLabel lblAsunto4;
    private javax.swing.JLabel lblAsunto5;
    private javax.swing.JLabel lblBienvenidoAdmin;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDestinatario1;
    private javax.swing.JLabel lblDestinatario2;
    private javax.swing.JLabel lblDestinatario3;
    private javax.swing.JLabel lblDestinatario4;
    private javax.swing.JLabel lblDestinatario5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblFecha3;
    private javax.swing.JLabel lblFecha4;
    private javax.swing.JLabel lblFecha5;
    private javax.swing.JLabel lblImagenAdmin;
    private javax.swing.JLabel lblMailTorneo;
    public javax.swing.JTextField txtConsultarMail;
    // End of variables declaration//GEN-END:variables
}
