CREATE DATABASE `TORNEOFUTBOL`;

CREATE TABLE TORNEOFUTBOL.JUGADOR (
	DOCUMENTO INT(10) NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	APELLIDO varchar(100) NOT NULL,
	TELEFONO INT(10) NULL,
	EMAIL varchar(100) NULL,
	POSICION varchar(30) NULL,
	MODO ENUM('ESTANDAR','SOLIDARIO') DEFAULT 'ESTANDAR' NOT NULL,
	SUSCRIPCION ENUM('OCASIONAL','FRECUENTE') DEFAULT 'OCASIONAL' NOT NULL,
	CONSTRAINT JUGADOR_PK PRIMARY KEY (DOCUMENTO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TORNEOFUTBOL.PARTIDO (
	ID INT UNSIGNED auto_increment NOT NULL,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ESTADO ENUM('PREPARACION','FINALIZADO') DEFAULT 'PREPARACION' NOT NULL,
	CONSTRAINT PARTIDO_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TORNEOFUTBOL.EQUIPO (
	ID INT UNSIGNED auto_increment NOT NULL,
	NUM_EQUIPO ENUM('1','2') NOT NULL,
	JUGADOR_1 INT NOT NULL,
	JUGADOR_2 INT NOT NULL,
	JUGADOR_3 INT NOT NULL,
	JUGADOR_4 INT NOT NULL,
	JUGADOR_5 INT NOT NULL,
	PARTIDO INT UNSIGNED NOT NULL,
	CONSTRAINT EQUIPO_PK PRIMARY KEY (ID),
	CONSTRAINT EQUIPO_JUGADOR_1_FK FOREIGN KEY (JUGADOR_1) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT EQUIPO_JUGADOR_2_FK FOREIGN KEY (JUGADOR_2) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT EQUIPO_JUGADOR_3_FK FOREIGN KEY (JUGADOR_3) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT EQUIPO_JUGADOR_4_FK FOREIGN KEY (JUGADOR_4) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT EQUIPO_JUGADOR_5_FK FOREIGN KEY (JUGADOR_5) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT EQUIPO_PARTIDO_FK FOREIGN KEY (PARTIDO) REFERENCES TORNEOFUTBOL.PARTIDO(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TORNEOFUTBOL.CALIFICACION (
	ID INT UNSIGNED auto_increment NOT NULL,
	DOCUMENTO_JUGADOR INT NOT NULL,
	PROMEDIO DOUBLE NOT NULL,
	CONSTRAINT CALIFICACION_PK PRIMARY KEY (ID),
	CONSTRAINT CALIFICACION_FK FOREIGN KEY (DOCUMENTO_JUGADOR) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TORNEOFUTBOL.DETALLE_CALIFICACION (
	ID INT UNSIGNED auto_increment NOT NULL,
	DOCUMENTO_CALIFICADOR INT NOT NULL,
	PUNTAJE INT NOT NULL,
	RELATO varchar(1000) NOT NULL,
	ID_CALIFICACION INT UNSIGNED NOT NULL,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT DETALLE_CALIFICACION_PK PRIMARY KEY (ID),
	CONSTRAINT DETALLE_CALIFICACION_JUGADOR_FK FOREIGN KEY (DOCUMENTO_CALIFICADOR) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT DETALLE_CALIFICACION_FK FOREIGN KEY (ID_CALIFICACION) REFERENCES TORNEOFUTBOL.CALIFICACION(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TORNEOFUTBOL.INFRACCION (
	ID INT UNSIGNED auto_increment NOT NULL,
	MOTIVO ENUM('MAL COMPORTAMIENTO','AGRESIVO','IRRESPONSABILIDAD','DAÑOS ESCENARIO E IMPLEMENTACION DEPORTIVA','OTROS') NOT NULL,
	RELATO varchar(1000) NOT NULL,
	DOCUMENTO_REPORTADOR INT NOT NULL,
	DOCUMENTO_INFRACCION INT NOT NULL,
	FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT INFRACCION_PK PRIMARY KEY (ID),
	CONSTRAINT INFRACCION_REPORTADOR_FK FOREIGN KEY (DOCUMENTO_REPORTADOR) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO),
	CONSTRAINT INFRACCION_JUGADOR_FK FOREIGN KEY (DOCUMENTO_INFRACCION) REFERENCES TORNEOFUTBOL.JUGADOR(DOCUMENTO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- INSERCION DE LOS JUGADORES

INSERT INTO `JUGADOR` VALUES
(1001, 'Luis', 'Diaz', 322401, 'luisdiaz01@selcolombia.com', 'Volante', 'ESTANDAR', 'FRECUENTE'),
(1002, 'Wilmar', 'Barrios', 322402, 'wilmarbarrios02@selcolombia.com', 'Volante', 'ESTANDAR', 'FRECUENTE'),
(1003, 'Davinson ', 'Sanchez', 322403, 'davinsonsanchez03@selcolombia.com', 'Defensa', 'ESTANDAR', 'FRECUENTE'),
(1004, 'Yerry', 'Mina', 322404, 'yerrymina04@selcolombia.com', 'Defensa', 'ESTANDAR', 'FRECUENTE'),
(1005, 'David ', 'Ospina', 322405, 'davidospina05@selcolombia.com', 'Arquero', 'ESTANDAR', 'FRECUENTE'),
(1006, 'Camilo', 'Vargas', 322406, 'camilovargas06@selcolombia.com', 'Arquero', 'ESTANDAR', 'FRECUENTE'),
(1007, 'Stefan', 'Medina', 322407, 'stefanmedina07@selcolombia.com', 'Lateral', 'ESTANDAR', 'FRECUENTE'),
(1008, 'Frank', 'Fabra', 322408, 'frankfabra08@selcolombia.com', 'Lateral', 'ESTANDAR', 'FRECUENTE'),
(1009, 'Juan', 'Quintero', 322409, 'juanquintero09@selcolombia.com', 'Volante', 'ESTANDAR', 'FRECUENTE'),
(1010, 'James', 'Rodriguez', 322410, 'jamesrodriguez10@selcolombia.com', 'Volante', 'ESTANDAR', 'FRECUENTE'),
(1011, 'Matheus', 'Uribe', 322411, 'matheusuribe11@selcolombia.com', 'Volante', 'SOLIDARIO', 'OCASIONAL'),
(1012, 'Radamel', 'Falcao', 322412, 'radamelfalcao12@selcolombia.com', 'Delantero', 'SOLIDARIO', 'OCASIONAL'),
(1013, 'Rafael', 'Borre', 322413, 'rafaelborre13@selcolombia.com', 'Delantero', 'SOLIDARIO', 'OCASIONAL'),
(1014, 'Luis', 'Muriel', 322414, 'luismuriel14@selcolombia.com', 'Delantero', 'SOLIDARIO', 'OCASIONAL'),
(1015, 'Miguel', 'Borja', 322415, 'miguelborja15@selcolombia.com', 'Delantero', 'SOLIDARIO', 'OCASIONAL'),
(1016, 'Duvan', 'Zapata', 322416, 'duvanzapata16@selcolombia.com', 'Delantero', 'SOLIDARIO', 'OCASIONAL'),
(1017, 'Edwin ', 'Cardona', 322417, 'edwincardona17@selcolombia.com', 'Volante', 'SOLIDARIO', 'OCASIONAL'),
(1018, 'Yimmi', 'Chara', 322418, 'yimmichara18@selcolombia.com', 'Volante', 'SOLIDARIO', 'OCASIONAL'),
(1019, 'Santiago', 'Arias', 322419, 'santiagoarias19@selcolombia.com', 'Lateral', 'SOLIDARIO', 'OCASIONAL'),
(1020, 'Abel', 'Aguilar', 322420, 'abelaguilar20@selcolombia.com', 'Volante', 'SOLIDARIO', 'OCASIONAL');